# -*- coding: utf-8 -*-
"""Tuna Over Fishing Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QgUG8g9oqWqNpBZbBZ_NQvSOe6sBg4lF
"""

import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

# Commented out IPython magic to ensure Python compatibility.
# %cd drive/MyDrive/Colab\ Notebooks/Project

tuna = pd.read_csv('tuna-landings.csv')

Tuna = tuna.drop(tuna.index[2827:5797], axis=0)

Tuna['Pounds']=Tuna['Pounds'].replace(",","", regex = True)

Tuna['Dollars']=Tuna['Dollars'].replace(",","", regex = True)

Tuna['Metric Tons']=Tuna['Metric Tons'].replace(",","", regex = True)

Tuna['Pounds'] = Tuna['Pounds'].astype(float)
Tuna['Metric Tons'] = Tuna['Metric Tons'].astype(float)
Tuna['Dollars'] = Tuna['Dollars'].astype(float)

"""### Intro

Tuna fishing has been around for many years, and some scientists believe that tuna fishing has been around for at least 2,000 years starting in the Mediterranean. The Tuna has been more than just a staple in the Pacific Islands and Japan it is more of a way of life. Tuna is used in most foods over in Japan and the Pacific island and as a matter of fact is a delicacy for them. But the growth of Tuna has not only grown overseas but especially started to take off in the states here due to its healthy benefits and low caloric attributes. With this the need for tuna has risen and sadley this means now tuna have been becoming overfished and now researchers are saying in the next few years it's possible to see tuna on the endangered species list.

### Analysis
"""

YearvsTons = Tuna.groupby('Year')['Metric Tons'].mean()

fig, ax = plt.subplots()

x = [2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021]
y = [321,313,279,375,289,267,299,346,311,322,315,288,327,328,306,368,329,338,294,266,292,210]

ax.plot(x,y, 'red')

ax.set_title("Tuna Caught In Metric Tons Over The Years")
ax.set_xlabel("Metric Tons")
ax.set_ylabel("Years")

plt.show()

"""Tuna has been growing in popularity in food, especially over the last couple of years. Therefore the demand for tuna fishing has been on the increase. In the graph, you can clearly tell the increase of tuna caught by the metric ton around 2015. But due to the increase in demand Tuna has slightly started to become very overfished and almost in danger, which the graph clearly shows by the year 2021 a huge drop in fish caught.

"""

tunaCounts = Tuna['NMFS Name'].value_counts()

fig, ax = plt.subplots()

ax.pie(tunaCounts, autopct = '%1.1f%%')

ax.legend(labels=['Yellowfin','Little Tunny','Albacore','Bluefin','Bigeye','Skipjack', 'Blackfin', 'Kawakwaw', 'Bluefin Pacific', 'Black Skipjack'],
          title = '2000 - 2021 Types of Tuna Caught', bbox_to_anchor=(0.9, 0.5, 0.3, 0.5))

ax.set_title('Breakdown of Tuna Caught')

plt.show()

"""This chart shows the breakdown of the percentage of type of fish caught between 2000-2021 and just gives you a perspective of what type of Tuna is fished the most.

"""

BFin = Tuna[Tuna['NMFS Name']== "TUNA, BLUEFIN"]

BFinMean = BFin.groupby('Year')['Metric Tons'].mean()

fig, ax = plt.subplots()

x = [2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021]
y = [299,293,120,137,132,84,43,89,58,134,152,121,51,61,64,61,154,117,93,210,127,99]

ax.plot(x,y, 'blue')

ax.set_title("Bluefin tuna Caught In Metric Tons Over The Years")
ax.set_xlabel("Metric Tons of BlueFin")
ax.set_ylabel("Years")

plt.show()

"""BlueFin tuna is one of the most fished Tuna in the world and is one of the most overfished Tuna as well. According to the World Wildlife Fund “Bluefin tuna populations have declined severely from overfishing and illegal fishing over the past few decades –not just Pacific bluefin tuna, but also Atlantic and Southern bluefin tuna. Population declines have been largely driven by the demand for this fish in high-end sushi markets, and their futures are uncertain.” (World Wildlife Fund, 2023). This could sadly mean a soon to be endangered to maybe extinct species in the next couple years.

"""

YFin = Tuna[Tuna['NMFS Name']== "TUNA, YELLOWFIN"]

MeanYFin=YFin.groupby('Year')['Metric Tons'].mean()

fig, ax = plt.subplots()

x = [2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021]
y = [640,570,340,590,381,441,447,588,496,434,422,353,514,392,417,474,394,771,578,293,558,373]

ax.plot(x,y, 'yellow')

ax.set_title("Yellowfin tuna Caught In Metric Tons Over The Years")
ax.set_xlabel("Metric Tons of Yellowfin")
ax.set_ylabel("Years")

plt.show()

"""Much like the Bluefin tuna, Yellowfin tuna have been the most caught tuna throughout the whole not only does my pie chart show that you can find this on many different sources. In the graph you can clearly see a decline in Metric Tons of YellowFin tuna caught. Even though between 2010 and 2021 you can see a big increase according to Katy Askew the Yellowfin tuna are being overfished and are declining in numbers by at least 20% and can be heading for collapse in 2026. Even Though they are not as endangered as Bluefin they are also on a steady decline.


"""

Com = Tuna[Tuna['Collection']== 'Commercial']
Rec = Tuna[Tuna['Collection']== 'Recreational']

"""I wanted to use these next two bar graphs to really hone in on what states should do their part in really trying to preserve the Yellow and BlueFin tunas number so that the states with the most tuna harvest from can then really try and do there part to preserve them.

"""

Com.groupby(['State','NMFS Name'])['Year'].count().unstack().fillna(0).drop(['TUNA, ALBACORE','TUNA, BIGEYE','TUNA, BLACKFIN',
                                                                             'TUNA, KAWAKAWA','TUNA, LITTLE TUNNY','TUNA, SKIPJACK','TUNA, BLUEFIN PACIFIC'], axis=1).plot(kind='bar')

plt.legend(fontsize = 10, loc = 'lower right')

plt.grid(axis = 'y')

plt.title('Commercially Caught Tuna')


plt.show()

"""For commmercially caught Tuna that states that really have to reconsider there regualtions or keep size are North Carolina, New York, New Jersey, New Hampshire, Massachusetts, Louisiana, Florida-west & east."""

Rec.groupby(['State','NMFS Name'])['Year'].count().unstack().fillna(0).drop(['TUNA, ALBACORE','TUNA, BIGEYE','TUNA, BLACKFIN',
                                                                             'TUNA, KAWAKAWA','TUNA, LITTLE TUNNY','TUNA, SKIPJACK','TUNA, BLACK SKIPJACK'], axis=1).plot(kind='bar')
plt.legend(fontsize = 10, loc = 'upper right')

plt.grid(axis = 'y')


plt.title('Recreational Caught Tuna')


plt.show()

"""And then for recreational the states that should rein in there regulations should be Virginia, North Carolina, New York, New Jersey, and Delaware.

### Conclusion

According to my analyses, tuna are on a negative decline and need our help to return them. Overfishing has been a huge problem and needs to be ended shortly especially commercially as their rules are a lot more lenient. Recreational fishing for tuna luckily has been becoming more and more strict and is being patrolled a lot more in this day of age. Without BlueFin and YellowFin, tuna ecosystems will be brought to the ground and the chain of command underwater will be thrown in the air and destroyed. Not only will the ecosystem be destroyed but many companies around the world would be forced to give up jobs and let people go causing more poverty and abandonment. Like the saying goes “Do not bite off the hand that feeds you”.

### Sources

Works Cited

Admin. “The History of Tuna.” In, 2 Aug. 2021, https://www.liveinhomecare.com/the-history-of-tuna/information/#:~:text=Tuna%20had%20been%20a%20staple,Animals%E2%80%9D%20written%20in%20350%20BC.
Foodnavigator.com. “Yellowfin Tuna 'Heading for Collapse' by 2026: A 20% Reduction in Catch Would Turn the Tide.” Foodnavigator.com, https://www.foodnavigator.com/Article/2021/03/18/Yellowfin-tuna-heading-for-collapse-by-2026-A-20-reduction-in-catch-would-turn-the-tide#:~:text=Yellowfin%20tuna%20in%20the%20Indian,are%20on%20a%20knife%2Dedge.
“Tuna.” WWF, World Wildlife Fund, https://www.worldwildlife.org/species/tuna#:~:text=Bluefin%20tuna%20populations%20have%20declined,and%20their%20futures%20are%20uncertain.
"""